// Generated by gencpp from file example/Telemetry.msg
// DO NOT EDIT!


#ifndef EXAMPLE_MESSAGE_TELEMETRY_H
#define EXAMPLE_MESSAGE_TELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example
{
template <class ContainerAllocator>
struct Telemetry_
{
  typedef Telemetry_<ContainerAllocator> Type;

  Telemetry_()
    : x(0)
    , y(0)
    , z(0)
    , alt(0)  {
    }
  Telemetry_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)
    , alt(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;

   typedef int32_t _alt_type;
  _alt_type alt;





  typedef boost::shared_ptr< ::example::Telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example::Telemetry_<ContainerAllocator> const> ConstPtr;

}; // struct Telemetry_

typedef ::example::Telemetry_<std::allocator<void> > Telemetry;

typedef boost::shared_ptr< ::example::Telemetry > TelemetryPtr;
typedef boost::shared_ptr< ::example::Telemetry const> TelemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example::Telemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example::Telemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::example::Telemetry_<ContainerAllocator1> & lhs, const ::example::Telemetry_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.alt == rhs.alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::example::Telemetry_<ContainerAllocator1> & lhs, const ::example::Telemetry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace example

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::example::Telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example::Telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example::Telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example::Telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example::Telemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example::Telemetry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a58464c5d1a0ed951c83d294f61a945";
  }

  static const char* value(const ::example::Telemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a58464c5d1a0ed9ULL;
  static const uint64_t static_value2 = 0x51c83d294f61a945ULL;
};

template<class ContainerAllocator>
struct DataType< ::example::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example/Telemetry";
  }

  static const char* value(const ::example::Telemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 z\n"
"int32 alt\n"
"\n"
;
  }

  static const char* value(const ::example::Telemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example::Telemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Telemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example::Telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example::Telemetry_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "alt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_MESSAGE_TELEMETRY_H
